### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Skyladd** [XenoNova/SkyBlockXT#14]
Fix Generator
===========
- [ ] Generate in its own world
- [ ] Beautify The Generator--New Shape
- [ ] Chest + Items

SkyLock - SkyBlock antiTroll and Protection System
==========================================
- [ ] Anti troll system: Since Some player may create IslandShops, there may be trolls that will want to kill you! like spawning in places you dont want to be spawned into!
- [ ] Island Protection: Protects the Island from being Destroyed by players, and allows to permit another player(s) to build and destroy
- [ ] Animal Protection: Good for Food Farming! and they wont kill your KillerBunny!

> SkyAuth Implemention
=====================
> - [ ] Implement SkyAuth

**Comment by TheKillerTacos** [comment]
Closing Because reuploading old plugin, I found out how to make it work!
