### ISSUE TITLE
[TODO for PRE-ALPHA] Feature list for Pre-Alpha (0.0.1)

### ISSUE THREAD

**Issue by TheKillerTacos** [XenoNova/SkyBlockXT#17]
[TODO] The Feature list that will have in Pre-Alpha
===================================
- [ ] Simple Generator (IsleGen 1.0)
- [ ] Island Protector (Islock 1.0)
- [ ] Mutli-Language support

[P.A Dev] Within Pre-Alpha Development todo Feature list:
====================================
- [ ] AntiTroll System 1.0
- [ ] Islock 2.0
- [ ] Faster World Generator (Generate chunks with blocks)
- [ ] Island Reset
- [ ] Island Delete*
- [ ] Skyland 1.0 (Replace IsleGen 1.0)
- [ ] Multi-World Support (Easy!)

**Comment by AndreTheGamer** [comment]
Hi, @TheKillerTacos  Can i help? like can i get on the team? to help out with this project. It seems unique

**Comment by TheKillerTacos** [comment]
Sure! Just wait until tomorrow Saturday, since I'm already on my bed :l haha

**Comment by AndreTheGamer** [comment]
@TheKillerTacos  Alright man.

**Comment by SkygridRex** [comment]
Well, i'm still don't understand anti-troll system

**Comment by TheKillerTacos** [comment]
Im making it because Long ago on a Server i had a Pretty bad experience, I was skyblocking and i needed some tools, but couldnt craft them but had a lot of in-game $$, so there was people selling and buying stuff, and you said like "Hey RandomDude88 tp to your isle!" and they tped you on their island, but there were somepeople that when you tp to their islands Either Killed you (There was an option to make your Island a PVP Arena. thats why this plugins was Called SkyBlockPVP so the Features would be focues on PVP but change the name since MCPE is really bad on PVP) or Burnt you on lava/fire,

So that was the Problem, And the reason that I will make the AntiTroll Sys, is to avoid so, and can be triggered, so people can make Other stuff if AntiTroll Sys gives problems,

What will it do? It will make you "Invinsible" and if you fall out of the world you Keep your Inv and XP, if somehow you die, you Keep your Inv and XP, and also you Can't attack anyone and vice versa, and Mobs cant attack you, If AI Implemented, but i guess the Mobs may still attack, Becuase the API and AI stuff, so thats the WHOLE explanation of the Anti-Troll System

**Comment by SkygridRex** [comment]
@TheKillerTacos I was Develop a SkyBlock Plugin with teams and refill system, actually i put here the generator if you want i could put the refill system and teams

**Comment by SkygridRex** [comment]
When you say kit, doyou refer items in the chest?

**Comment by TheKillerTacos** [comment]
Yes, but also ill add a Kit system, and the Main Purpose of this plugin, is to Make it general, so no more plugins will be needed, soon at BETA stage i will add a simple economy system with shops

**Comment by SkygridRex** [comment]
i'm still not understand

**Comment by TheKillerTacos** [comment]
i'll replace the Skyblock Generator, Add teams and when i finish the changes im making, add chest **Fill**,

**Comment by SkygridRex** [comment]
so i most add chest fill

**Comment by TheKillerTacos** [comment]
Yes, in this line: https://github.com/XenoNova/SkyBlockXT/blob/master/src/SkyBlockXT/Tools/IsleGen.php#L210

**Comment by TheKillerTacos** [comment]
Going to delete Unecessary comments

**Comment by SkygridRex** [comment]
Anti Troll Sytem can be supplied with factions plugin code (i think)

**Comment by TheKillerTacos** [comment]
well, No, it will actually require IsLock, since it wil check for player location, if its in the area of another player island it will enable KeepInventory And KeepXp and will just add 10,000 of life then after 2 minutes it will disable that and get life back to 20, The Keepinventory and XP stuff will be taken from KeepINV (See repo at XenoNova) and IsLock will later created

**Comment by SkygridRex** [comment]
Explicame para que es el IsLock

**Comment by TheKillerTacos** [comment]
IsLock: Protege las islas para que solo los dueños de la isla puedan modificarla y añadir amigos para que puedan modificar la isla,

**Comment by SkygridRex** [comment]
Saquemolos del factions

**Comment by Skyladd** [comment]
Once php7 support is added I can start to help with this list.

**Comment by Blubberboy333** [comment]
I added an island generator

**Comment by TheKillerTacos** [comment]
@Blubberboy333 long ago i fixed the setBlock code, i guess that it got lost when i deleted Skyland, or is Skyland is till there?

**Comment by Blubberboy333** [comment]
SkyLand is still there

**Comment by Skyladd** [comment]
To add a chest to the island you have to register it as a tile otherwise it will be invisible EXAMPLE: 

$block = new Chest();
                $sender->getLevel()->setBlock(new Vector3($XKiste, $YKiste, $ZKiste), $block, true, true);
                $nbt = new CompoundTag("", [
                    new ListTag("Items", []),
                    new StringTag("id", Tile::CHEST),
                    new IntTag("x", $XKiste),
                    new IntTag("y", $YKiste),
                    new IntTag("z", $ZKiste)
                ]);
                $nbt->Items->setTagType(NBT::TAG_Compound);
                $tile = Tile::createTile("Chest", $sender->getLevel()->getChunk($XKiste >> 4, $ZKiste >> 4), $nbt);

**Comment by TheKillerTacos** [comment]
PLUGIN WILL BE REMADE ON POCKETPANEL. AND TKRT CREATIONS WILL BE DELETED, BUT ILL KEEP THE NAME,

**Comment by SkygridRex** [comment]
Espera... que?

**Comment by SkygridRex** [comment]
Justo cuando aprendo a programar en html y algo de css ocurre esto.
@TheKillerTacos what is happening

**Comment by AndreTheGamer** [comment]
@SkygridRex 
Usted está inclinado o ya ha aprendido html / css ?

**Comment by SkygridRex** [comment]
@AndreTheGamer i think you have used google transistor, but yes,  but i didnt like use css because sometimes It's very difficult

**Comment by AndreTheGamer** [comment]
@Skyladd Yes i did :+1:  and also CSS isn't that hard. I learned it on CodeAcadamy along with PHP it's very simple if you complete lessons daily! or even multiple(S) :o:

**Comment by SkygridRex** [comment]
me too

**Comment by TheKillerTacos** [comment]
Im deleting the plugin to recode it, since it will take more time fixing it and updating it rather than rebuilding it, i will add more security also, soon i will rebuild this, im going to delete this Organizations,

Since like i said to @AndreTheGamer, that TKRT Creations main purpose wasn't for Open Source Projects, more like Crations, closed and finished stuff, so we will go to PocketProjects, which will be mostly based on PocketMine Plugins and Tools
