### ISSUE TITLE
[TODO] Todo for 1.0.0 BETA

### ISSUE THREAD

**Issue by TheKillerTacos** [XenoNova/SkyBlockXT#2]
TODO:

- [ ] PHP7 Support

- [ ] Automatic Backup*

- [ ] Finish up for 1.0.0

Commands 
----------------------
- [ ] /is - main Skyblock command
- [ ] /is create - Creates a island
- [ ] /is delete - deletes a island
- [ ] /is get - Gets player island location
- [ ] /is help - shows all commands of SkyblockPVP
- [ ] /is team - shows your island team list (your island)
   - [ ] /is invite @player - adds player
   - [ ] /is allow @player - triggers for editing island
   - [ ] /is remove @player - removes a player
- [ ] /is kick @player - kicks specified player from island
- [ ] /is warp (player) - warps a player to a island
   - [ ] /is warp <on/off> - turns on or off warp features on your island
   - [ ] /is setwarp - sets warp spawnpoint.

Functions:
---------

- [ ] SkyLand Generator (Generates up to 100 islands in a world)
- [ ] IsleGen LIVE Generator (Generates the island, not the world)
- [ ] WipeIS - Island Wiper,

SkyFeatures
------------------
- [ ] SkyMode (Anti-Troll system for warping)
- [ ] SkyProtector - Skyland Protector, Can be attached to Economy system
- [ ] $kyEconomy (Economy System more details at blog)
- [ ] SkyAuth Implemention (For island Protection)

Weird but awesome stuff!:
---------------------------------
- [ ] [Welcome] Signs instead of /warp on/off
- [ ] SECRETS :L

>*Configurable
--------
* - [ ] Island Plot Size
* - [ ] Multiple Island Generator
* - [ ] SafeMode (Anti-Troll system for warping)

**Comment by XiangZhao969** [comment]
Thanks for remaking this plugin :)

**Comment by TheKillerTacos** [comment]
No problem. Tomorrow I'll be ending the fixing. So it should be done by tomorrow. I'll make another folder for English plugin..

**Comment by XiangZhao969** [comment]
Nice!

**Comment by Skyladd** [comment]
Can't wait till PHP7 support this is the only plugin ive found that seems like bukkits askyblock plugin

**Comment by TheKillerTacos** [comment]
Hehe, im finishing up the Multilanguage support, later ill fix most of the errors.

**Comment by Skyladd** [comment]
So what are this islands shaped like? I really want to use this plugin lol, i found another one but it looked like a sandwich with sand in the middle xD.

**Comment by TheKillerTacos** [comment]
Kind of like a sandwich, but ill change the code to make the New island like:
![maxresdefault](https://cloud.githubusercontent.com/assets/14338036/13191443/53b77998-d729-11e5-9d22-0ecc13b26cc4.jpg)

**Comment by Skyladd** [comment]
Nice i wish i could help but i have no experience in php lol. hope to see php7 soon :)

**Comment by TheKillerTacos** [comment]
ok, im also waiting for php7, to start Updating the plugins, but now lets wait for so.

**Comment by Skyladd** [comment]
i have very little experience in html. i could maybe help with the wiki? Did you plan on making the wiki on some hosting website for wikis or make a website from scratch?

**Comment by TheKillerTacos** [comment]
Maybe in github, but let me make a issue and talk on that one

**Comment by TheKillerTacos** [comment]
[NOTICE] Soon ill Transfer this Repo at http://github.com/TKRT-Creations/SkyBlockPVP!

**Comment by Adam1609** [comment]
Still waiting for 1.0.0 men!!!

**Comment by Skyladd** [comment]
We are working on it :D

**Comment by TheKillerTacos** [comment]
What the heck, i added a comment in here, why isnt it here? but yea we are working on it...

**Comment by TheKillerTacos** [comment]
REMAKING PLUGIN! FOR SAKE GOD THIS IS FRUSTATING!
